project:
  type: website

website:
  title: "STARS Quarto Tutorial"

  sidebar:
    background: "#ca5d3f"
    style: "docked"
    contents:
      - index.qmd
      - pages/examples.qmd

format:
  html:
    theme:
      - lumen
