project:
  type: website

website:
  title: "Introduction to Quarto for Research Projects"
  favicon: images/daffodil_head.png
  page-navigation: true
  navbar:
    title: "Introduction to Quarto for Research Projects"
    right:
      - icon: github
        text: "GitHub"
        href: https://github.com/pythonhealthdatascience/quarto-tutorial
  announcement:
    icon: info-circle
    content: "This tutorial was developed as part of the <a href='https://pythonhealthdatascience.github.io/stars/' target='_blank'>STARS project</a>."
    position: below-navbar
    dismissable: false
  sidebar:
    style: docked
    contents:
      - text: Welcome
        href: index.qmd
      - text: "Slides: Why make a website for your research?"
        href: pages/why/index.qmd
      - section: "Tutorial"
        contents:
          - pages/setup/index.qmd
          - pages/basic_structure/index.qmd
          - pages/making_a_change/index.qmd
          - pages/markdown/index.qmd
          - pages/quarto_features/index.qmd
          - pages/media/index.qmd
          - pages/inline_html/index.qmd
          - pages/customising/index.qmd
      - pages/task/index.qmd
      - section: "Optional extras"
        contents:
          - pages/code/index.qmd
          - pages/blog/index.qmd
      - pages/examples/index.qmd
  page-footer:
    center:
      - text: |
          Code licence: <a href="https://opensource.org/license/mit" target="_blank" rel="noopener">MIT</a>.  
          Text licence: <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC-BY-SA 4.0</a>.

format:
  html:
    number-sections: true
    lightbox: true
    theme:
      - cosmo
      - styles/theme.scss
    css:
      - styles/styles.css
    include-after-body:
      - styles/slideshow.js