project:
  type: website

website:
  title: "Introduction to Quarto for Research Projects"
  sidebar:
    title: "Introduction to Quarto for Research Projects"
    style: "docked"
    contents:
      - text: Welcome
        href: index.qmd
      - section: "Tutorial"
        contents:
          - pages/setup.qmd
      - pages/examples.qmd

format:
  html:
    theme:
      - cosmo
      - theme.scss
