---
title: Listings (e.g., blog)
listing:
  - id: simple
    contents: examples
    type: grid
    grid-columns: 3
  - id: links
    contents: links_real.yml
    template: links.ejs
---


::: {.pale-blue}

**On this page we will:**

* Create a simple listing of pages (e.g., for a blog).
* Create a grouped listing of pages.
* Build a more advanced listing to external pages using a YAML file and EJS template.

:::

A [listing](https://quarto.org/docs/reference/projects/websites.html#listings) is a Quarto feature that automatically builds a list or grid of items for you.

There are two ways to use listings:

1. To show a list of **pages from your site** (e.g., a blog index listing all your posts).
2. To show a list of **external things** (e.g., interesting projects or resources you link out to).

## Listing of pages

### Simple listing of pages

A common use case is a blog or "Projects" page that lists documents from a folder. We create it with `listing:` in the YAML. At a minimum, you specify `contents`, which determines which documents to include.

For example, this will create a listing from files within the `pages/` folder:

```{.markdown}
---
title: Projects
listing:
  contents: pages
---
```

In this example, we have add more criteria:

* `type:` how to display the items (for example, `default` list or `grid`).
* `grid-columns:` number of columns when using a grid layout.
* `fields:` which pieces of metadata to show for each item (for example, `title`, `subtitle`, `image`).
* `image-height:` how tall to show any image field.

```{.markdown}
---
title: Projects
listing:
  contents: pages
  type: grid
  grid-columns: 3
  fields: [title, subtitle, image]
  image-height: "100"
---
```

Example:

::: {#simple}
:::

### Grouped listing of pages

You can also define **multiple listings** on the same page and group them.

This approach assumes that the pages in `pages/` have a `year:` field in their YAML. Each listing block uses `include:` to filter by `year`, and an `id` that matches a placeholder div later in the document.

```{.markdown}
---
title: Projects
listing:
  - id: projects-2026
    contents: pages
    include:
      year: 2026
    fields: [title, subtitle, image]

  - id: projects-2025
    contents: pages
    include:
      year: 2025
    fields: [title, subtitle, image]

  - id: projects-2024
    contents: pages
    include:
      year: 2024
    fields: [title, subtitle, image]

format:
  html:
    page-layout: article
---

## 2026

::: {#projects-2026}
:::

## 2025

::: {#projects-2025}
:::

## 2024

::: {#projects-2024}
:::
```

## Listing of external things

**Note:** This is more advanced. The approach is based on `quarto-dev/quarto-web`'s gallery ([link](https://github.com/quarto-dev/quarto-web/blob/main/docs/gallery/gallery.ejs)).

### Create a YAML file of links

First, create a YAML file (e.g., `links.yml`). This contains the data for your listing page - the content your want to show, such as descriptions, links, and titles - while the page layout is handled separately by Quarto and the template below.

In this example, each top-level `- category:` blcok is one section of the listing. Inside each section, the `tiles:` field contains the individual cards you want to display, and each card can have fields such as `title`, `subtitle`, `href`, and `thumbnail`.

For example:

```{.yaml}
{{< include links.yml >}}
```

### Create an EJS file

Next, create an EJS template file (e.g., `links.ejs`). This file tells Quarto **how to display** the data from `links.yml`, so you can think of it as the layout or "recipe" for turning your YAML data into HTML on the page.

For example:

````{.txt}
{{< include links.ejs >}}
````

### Create the `.qmd` page

Now create the Quarto page that will display the listing. This page connects the data file (`links.yml`) to the template file (`links.ejs`) and tells Quarto where the finished listing should be inserted.

The `::: {#links}` div is where Quarto injects the rendered listing ofr the listing configuration with the same `id`.

```{.md}
---
title: Listing
listing:
  - id: links
    contents: links.yml
    template: links.ejs
---

::: {#links}
:::
```

To include the page in your site, add the `.qmd` file to `_quarto.yml`

### Example

::: {#links}
:::